name: hourz
description: 'Hourz Marketplace'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 # iOS style icons.

  # State Management
  flutter_riverpod: ^2.4.9

  # HTTP Client
  dio: ^5.4.0

  # Routing
  go_router: ^14.2.7

  # Environment Variables
  flutter_dotenv: ^5.1.0

  logger: ^2.6.1

  # Immutable Data Classes
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.4

  # Image Picker
  image_picker: ^1.0.4

  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # Location Services
  location: ^5.0.3
  lucide_icons: ^0.257.0
  # Maps (Optional for future)
  # flutter_map: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.5.8
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: IBM_Plex_Sans_Thai
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_Thai/IBMPlexSansThai-Light.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Thai/IBMPlexSansThai-Regular.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Thai/IBMPlexSansThai-Medium.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Thai/IBMPlexSansThai-SemiBold.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Thai/IBMPlexSansThai-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icons/hourz_icon_light.png'
