"""Add created_at to Province

Revision ID: 49a196e0696c
Revises: 1b79aaf7dfd5
Create Date: 2025-09-20 23:00:41.240407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a196e0696c'
down_revision: Union[str, None] = '1b79aaf7dfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('province', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('province', 'created_at')
    # ### end Alembic commands ###
