"""Add UploadedFile model

Revision ID: b683d6b5b887
Revises: 
Create Date: 2025-09-28 21:05:46.775663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b683d6b5b887'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadedfile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(), nullable=False),
    sa.Column('upload_category', sa.VARCHAR(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploadedfile_filename'), 'uploadedfile', ['filename'], unique=False)
    op.create_index(op.f('ix_uploadedfile_is_active'), 'uploadedfile', ['is_active'], unique=False)
    op.create_index(op.f('ix_uploadedfile_upload_category'), 'uploadedfile', ['upload_category'], unique=False)
    op.create_index(op.f('ix_uploadedfile_uploaded_at'), 'uploadedfile', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_uploadedfile_uploaded_by'), 'uploadedfile', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_uploadedfile_uploaded_by'), table_name='uploadedfile')
    op.drop_index(op.f('ix_uploadedfile_uploaded_at'), table_name='uploadedfile')
    op.drop_index(op.f('ix_uploadedfile_upload_category'), table_name='uploadedfile')
    op.drop_index(op.f('ix_uploadedfile_is_active'), table_name='uploadedfile')
    op.drop_index(op.f('ix_uploadedfile_filename'), table_name='uploadedfile')
    op.drop_table('uploadedfile')
    # ### end Alembic commands ###
